# Generated by Django 4.2.7 on 2023-12-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cartItem',
        ),
    ]
