# Generated by Django 4.2.7 on 2023-11-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='pics')),
                ('less_time', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('st_num', models.CharField(max_length=200)),
                ('msg_num', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
